-- 029_benefits_jsonb_hotfix.sql
-- 🔴 HOTFIX: 028 마이그가 benefits에 TEXT[] 넣어서 발생한 타입 에러 수정
-- memberships.benefits는 JSONB 타입 (003_members.sql), 018 마이그가 jsonb_build_array로 바꿨으나
-- 028에서 ARRAY[...]::TEXT[]로 회귀. 모든 자동/수동 발급 실패 중.
-- 해결: auto_issue_membership / issue_membership 함수에서 jsonb_build_array 사용하도록 재정의.

-- (1) auto_issue_membership (028 기반, benefits만 jsonb_build_array로 교체)
DROP FUNCTION IF EXISTS public.auto_issue_membership() CASCADE;
CREATE FUNCTION public.auto_issue_membership() RETURNS TRIGGER LANGUAGE plpgsql SECURITY DEFINER AS $fn_029_aim$ DECLARE v_member_id UUID; v_code TEXT; v_plots INT; v_attempts INT := 0; v_new_id UUID; BEGIN IF NEW.payment_status = '납부완료' AND (OLD.payment_status IS NULL OR OLD.payment_status <> '납부완료') THEN IF NEW.member_id IS NOT NULL THEN v_member_id := NEW.member_id; ELSE SELECT m.id INTO v_member_id FROM public.members m JOIN public.customers c ON public.normalize_phone(m.phone) = public.normalize_phone(c.phone) WHERE c.id = NEW.customer_id LIMIT 1; END IF; IF v_member_id IS NOT NULL THEN IF NOT EXISTS (SELECT 1 FROM public.memberships WHERE member_id = v_member_id AND farm_id = NEW.farm_id AND status = 'active') THEN BEGIN LOOP v_code := 'poco-' || LPAD(FLOOR(RANDOM() * 1000000)::TEXT, 6, '0'); v_attempts := v_attempts + 1; EXIT WHEN NOT EXISTS (SELECT 1 FROM public.memberships WHERE membership_code = v_code) OR v_attempts >= 20; END LOOP; SELECT plots INTO v_plots FROM public.plans WHERE name = NEW.plan LIMIT 1; IF v_plots IS NULL THEN v_plots := CASE NEW.plan WHEN '씨앗' THEN 1 WHEN '새싹' THEN 2 WHEN '자람' THEN 3 ELSE 1 END; END IF; INSERT INTO public.memberships (member_id, membership_code, farm_id, plots, start_date, end_date, status, benefits, plan_name) VALUES (v_member_id, v_code, NEW.farm_id, v_plots, COALESCE(NEW.start_date, CURRENT_DATE), COALESCE(NEW.end_date, CURRENT_DATE + INTERVAL '1 year'), 'active', jsonb_build_array('에어바운스 / 키즈놀이터 / 모래놀이터 무료 이용','동물 먹이주기 체험 무료','하계철 수영장 무료 이용','동계철 눈썰매장 할인권 제공','전기 수도 농기구 무상 이용','포코러쉬 풀빌라 할인권 제공'), NEW.plan) RETURNING id INTO v_new_id; INSERT INTO public.membership_logs (membership_id, action, to_status, to_start, to_end) VALUES (v_new_id, 'issued', 'active', NEW.start_date, NEW.end_date); EXCEPTION WHEN OTHERS THEN RAISE WARNING 'auto_issue_membership failed for rental %: %', NEW.id, SQLERRM; END; END IF; END IF; END IF; RETURN NEW; END; $fn_029_aim$;

DROP TRIGGER IF EXISTS auto_issue_membership_trigger ON public.farm_rentals;
CREATE TRIGGER auto_issue_membership_trigger AFTER INSERT OR UPDATE OF payment_status ON public.farm_rentals FOR EACH ROW EXECUTE FUNCTION public.auto_issue_membership();

-- (2) issue_membership (수동 발급)
DROP FUNCTION IF EXISTS public.issue_membership(UUID);
CREATE FUNCTION public.issue_membership(p_rental_id UUID) RETURNS UUID LANGUAGE plpgsql SECURITY DEFINER AS $fn_029_issue$ DECLARE v_rental RECORD; v_member_id UUID; v_code TEXT; v_plots INT; v_attempts INT := 0; v_new_id UUID; BEGIN SELECT * INTO v_rental FROM public.farm_rentals WHERE id = p_rental_id; IF NOT FOUND THEN RAISE EXCEPTION 'RENTAL_NOT_FOUND'; END IF; IF v_rental.member_id IS NOT NULL THEN v_member_id := v_rental.member_id; ELSE SELECT m.id INTO v_member_id FROM public.members m JOIN public.customers c ON public.normalize_phone(m.phone) = public.normalize_phone(c.phone) WHERE c.id = v_rental.customer_id LIMIT 1; END IF; IF v_member_id IS NULL THEN RAISE EXCEPTION 'MEMBER_NOT_LINKED'; END IF; IF EXISTS (SELECT 1 FROM public.memberships WHERE member_id = v_member_id AND farm_id = v_rental.farm_id AND status = 'active') THEN RAISE EXCEPTION 'ACTIVE_MEMBERSHIP_EXISTS'; END IF; LOOP v_code := 'poco-' || LPAD(FLOOR(RANDOM() * 1000000)::TEXT, 6, '0'); v_attempts := v_attempts + 1; EXIT WHEN NOT EXISTS (SELECT 1 FROM public.memberships WHERE membership_code = v_code) OR v_attempts >= 20; END LOOP; SELECT plots INTO v_plots FROM public.plans WHERE name = v_rental.plan LIMIT 1; IF v_plots IS NULL THEN v_plots := CASE v_rental.plan WHEN '씨앗' THEN 1 WHEN '새싹' THEN 2 WHEN '자람' THEN 3 ELSE 1 END; END IF; INSERT INTO public.memberships (member_id, membership_code, farm_id, plots, start_date, end_date, status, benefits, plan_name) VALUES (v_member_id, v_code, v_rental.farm_id, v_plots, COALESCE(v_rental.start_date, CURRENT_DATE), COALESCE(v_rental.end_date, CURRENT_DATE + INTERVAL '1 year'), 'active', jsonb_build_array('에어바운스 / 키즈놀이터 / 모래놀이터 무료 이용','동물 먹이주기 체험 무료','하계철 수영장 무료 이용','동계철 눈썰매장 할인권 제공','전기 수도 농기구 무상 이용','포코러쉬 풀빌라 할인권 제공'), v_rental.plan) RETURNING id INTO v_new_id; INSERT INTO public.membership_logs (membership_id, action, to_status, to_start, to_end, reason, changed_by) VALUES (v_new_id, 'manual_issue', 'active', v_rental.start_date, v_rental.end_date, 'manual', auth.uid()); RETURN v_new_id; END; $fn_029_issue$;

GRANT EXECUTE ON FUNCTION public.issue_membership(UUID) TO authenticated;

-- 롤백: 028 함수 CREATE OR REPLACE 재실행 (권장하지 않음)
